DROP TABLE IF EXISTS `settings`;
CREATE TABLE settings
(
  name         VARCHAR(50) PRIMARY KEY NOT NULL,
  type         ENUM ('STRING_VALUE', 'INT_VALUE', 'BOOL_VALUE', 'FLOAT_VALUE'),
  STRING_VALUE TEXT,
  INT_VALUE    INTEGER,
  BOOL_VALUE   BOOL,
  FLOAT_VALUE  FLOAT
);

INSERT INTO settings (name, type, STRING_VALUE, INT_VALUE, BOOL_VALUE, FLOAT_VALUE) VALUES
  ('SHOW_PLAYER_FEEDBACK', 'BOOL_VALUE', NULL, NULL, FALSE, NULL),
  ('REGISTRATION', 'BOOL_VALUE', NULL, NULL, TRUE, NULL),
  ('CLASS_UPLOAD', 'BOOL_VALUE', NULL, NULL, TRUE, NULL),
  ('GAME_CREATION', 'BOOL_VALUE', NULL, NULL, TRUE, NULL),
  ('REQUIRE_MAIL_VALIDATION', 'BOOL_VALUE', NULL, NULL, FALSE, NULL),
  ('SITE_NOTICE', 'STRING_VALUE', 'please add a site notice', NULL, NULL, NULL),
  ('PASSWORD_RESET_SECRET_LIFESPAN', 'INT_VALUE', NULL, 12, NULL, NULL),
  ('MIN_PASSWORD_LENGTH', 'INT_VALUE', NULL, 8, NULL, NULL),
  ('CONNECTION_POOL_CONNECTIONS', 'INT_VALUE', NULL, 20, NULL, NULL),
  ('CONNECTION_WAITING_TIME', 'INT_VALUE', NULL, 5000, NULL, NULL),
  ('EMAIL_SMTP_HOST', 'STRING_VALUE', '', NULL, NULL, NULL),
  ('EMAIL_SMTP_PORT', 'INT_VALUE', '', NULL, NULL, NULL),
  ('EMAIL_ADDRESS', 'STRING_VALUE', '', NULL, NULL, NULL),
  ('EMAILS_ENABLED', 'BOOL_VALUE', NULL, NULL, FALSE, NULL),
  ('DEBUG_MODE', 'BOOL_VALUE', NULL, NULL, FALSE, NULL),
  ('EMAIL_PASSWORD', 'STRING_VALUE', '', NULL, NULL, NULL),
  ('AI_STRAT', 'STRING_VALUE', 'KILLCOUNT', NULL, NULL, NULL),
  ('AI_DEFENDER_POINTS_DIFFERENCE', 'INT_VALUE', NULL, 5, NULL, NULL),
  ('AI_ATTACKER_POINTS_DIFFERENCE', 'INT_VALUE', NULL, 5, NULL, NULL),
  ('AI_TEST_MUTANT_RELATION', 'FLOAT_VALUE', NULL, NULL, NULL, 2);
